// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrzmFEZSI0swDmbcYw9108Ag8iRyrEKr8',
    appId: '1:153734490852:web:d1829d9a1f78959e609af1',
    messagingSenderId: '153734490852',
    projectId: 'bookmark-bca',
    authDomain: 'bookmark-bca.firebaseapp.com',
    storageBucket: 'bookmark-bca.firebasestorage.app',
    measurementId: 'G-FDN836SXLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqZaF3NfMqKivGntrCEdb5eXOg3ViULkc',
    appId: '1:153734490852:android:eeb6465023c108e8609af1',
    messagingSenderId: '153734490852',
    projectId: 'bookmark-bca',
    storageBucket: 'bookmark-bca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-m5kGf-9OXMB50-0xEjGXI6nqyO9D27o',
    appId: '1:153734490852:ios:85b410dc8912ab19609af1',
    messagingSenderId: '153734490852',
    projectId: 'bookmark-bca',
    storageBucket: 'bookmark-bca.firebasestorage.app',
    iosBundleId: 'com.example.bookmark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-m5kGf-9OXMB50-0xEjGXI6nqyO9D27o',
    appId: '1:153734490852:ios:85b410dc8912ab19609af1',
    messagingSenderId: '153734490852',
    projectId: 'bookmark-bca',
    storageBucket: 'bookmark-bca.firebasestorage.app',
    iosBundleId: 'com.example.bookmark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrzmFEZSI0swDmbcYw9108Ag8iRyrEKr8',
    appId: '1:153734490852:web:d8249e6d6c36e2be609af1',
    messagingSenderId: '153734490852',
    projectId: 'bookmark-bca',
    authDomain: 'bookmark-bca.firebaseapp.com',
    storageBucket: 'bookmark-bca.firebasestorage.app',
    measurementId: 'G-ZC709C2S1D',
  );
}
